# Generated by Django 2.2.1 on 2019-05-24 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="The name of the street.", max_length=100
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="The number of the building.", max_length=25
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("fax", models.CharField(max_length=30)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name of the company.", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any notes you want to keep for this company.",
                        null=True,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("fax", models.CharField(max_length=30)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any notes you want to keep for this contact.",
                        null=True,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the product.", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description for the product.",
                        null=True,
                    ),
                ),
                (
                    "built_on",
                    models.DateField(
                        blank=True,
                        help_text="The date the product was built or first released.",
                        null=True,
                    ),
                ),
                (
                    "built_in",
                    models.CharField(
                        blank=True,
                        help_text="The country the product was built in.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The order in which products are shown, in ascending order.",
                        null=True,
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="Products which are archived are not shown.",
                    ),
                ),
                (
                    "built_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which company built this product.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klanad.Company",
                    ),
                ),
            ],
            options={"ordering": ("position",)},
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="products/%Y/%m/%d")),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The order in which images are shown, in ascending order.",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="klanad.Product"
                    ),
                ),
            ],
            options={"ordering": ("position",)},
        ),
        migrations.AddField(
            model_name="company",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klanad.Contact",
            ),
        ),
    ]
