# Generated by Django 2.2.2 on 2019-06-06 09:21

from django.db import migrations
from django.db.models import FileField


class Migration(migrations.Migration):

    dependencies = [("klanad", "0002_auto_20190527_1816")]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=FileField(upload_to="products/%Y/%m/%d"),
        )
    ]
