# Generated by Django 2.2.2 on 2019-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("klanad", "0011_auto_20190613_1136")]

    operations = [
        migrations.AddField(
            model_name="groupcontainer",
            name="title_de",
            field=models.CharField(
                help_text="The title of the product.", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="groupcontainer",
            name="title_en",
            field=models.CharField(
                help_text="The title of the product.", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="groupcontainer",
            name="title_fr",
            field=models.CharField(
                help_text="The title of the product.", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="groupcontainer",
            name="title_nl",
            field=models.CharField(
                help_text="The title of the product.", max_length=256, null=True
            ),
        ),
    ]
