# Generated by Django 2.2.2 on 2019-06-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("klanad", "0012_auto_20190613_1146")]

    operations = [
        migrations.AlterModelOptions(
            name="groupcontainer", options={"ordering": ("position",)}
        ),
        migrations.AddField(
            model_name="groupcontainer",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The order in which containers are shown, in ascending order.",
                null=True,
            ),
        ),
    ]
