# Generated by Django 2.2.2 on 2019-06-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klanad', '0013_auto_20190613_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ('container', 'position')},
        ),
    ]
