# Generated by Django 2.2.2 on 2019-06-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klanad', '0014_auto_20190613_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('group', 'position')},
        ),
    ]
